### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gbazilio**
needed step to a successful usage

### CODE REVIEW

**Comment by gbazilio** [comment]
I've wasted some time trying to 'directly' use it as scpecified in usage section and I found out I needed to add an item to my base theme/style. It can save time for others.

**Comment by castorflex** [comment]
Actually, you should be able to use it without any theme, but be sure so set `android:indeterminateOnly="true"`.

**Comment by gbazilio** [comment]
Hmm...I tried what you said but after removing the "cpbStyle" style tag from styles.xml the progress bar vanishes. :(

**Comment by castorflex** [comment]
Can you try the following?

```xml
<fr.castorflex.android.circularprogressbar.CircularProgressBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:indeterminateOnly="true"
            android:minHeight="48dp"
            android:maxHeight="48dp"
            android:maxWidth="48dp"
            android:minWidth="48dp"
            app:cpb_colors="@array/gplus_colors"/>
```

If that doesn't work, can you create a sample project with your issue and send it to me?
Thank you.

**Comment by gbazilio** [comment]
The snippet you sent me works! :) Thanks!

I'll check this later.

**Pull request closed without merging**
